orbs:
  maven: circleci/maven@1.4.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: "clean install"
          executor:
            name: maven/default
            tag: "11.0"
