orbs:
  maven: circleci/maven@1.4.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - checkout
      - maven/with_cache:
          command: "mvn clean install"
          executor:
            name: maven/default
            tag: "11.0"
