orbs:
  maven: circleci/maven@1.4.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: "-X clean install site"
          executor:
            name: maven/default
            tag: "11.0"
          test_results_path: target/surefire-reports
