orbs:
  maven: circleci/maven@1.4.1
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: "-X clean install site"
          executor:
            name: maven/default
            tag: "11.0"
      - run:
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          name: Save test results
          when: always
      - store_test_results:
          path: ~/test-results
