---
blank_issues_enabled: false
contact_links:
  - name: Ask a question or start a discussion
    url: https://github.com/twlabs/Cookiecutter-Templater-for-Backstage/wiki
    about: Use the Github discussions feature
