name: 🔧 Just a issue.
labels: ["issue"]
title: "[Issue]: "
assignees:
  - luiz-micci
  - peppetwer
description: Elaborate about your issue.
body:
  - type: textarea
    id: desc
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks for collaborate 🙏
